name: posts-daily

on:
  workflow_dispatch:
  schedule:
    - cron:  '12 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install firefox
      - name: Clone content repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.CONTENT_REPOSITORY_OWNER }}/${{ secrets.CONTENT_REPOSITORY_NAME }}
          token: ${{ secrets.TOKEN }}
          path: ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Delete existing content to track deleted posts
        run: rm -f posts/*.html
        working-directory: ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Get current content
        run: python posts.py ${{ secrets.SITE_BASE_URL }} ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit new files
        run: if [ -n "$(git ls-files --others)" ];
          then
            git ls-files --others | xargs git add --all;
            git commit -m "🟢 new files";
          fi
        working-directory: ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Commit modified files
        run: if [ -n "$(git ls-files --modified)" ];
          then
            git ls-files --modified | xargs git add --all;
            git commit -m "🟡 modified files";
          fi
        working-directory: ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Commit deleted files
        run: if [ -n "$(git ls-files --deleted)" ];
          then
            git ls-files --deleted | xargs git add --all;
            git commit -m "🔴 deleted files";
          fi
        working-directory: ${{ secrets.CONTENT_REPOSITORY_NAME }}
      - name: Push changes
        run: git push
        working-directory: ${{ secrets.CONTENT_REPOSITORY_NAME }}
